server:
  port: 7900
eureka:
  instance:
    hostname: localhost
  client:
  #声明是否将自己的信息 注册到eureka服务器上

    #是否到Eureka 服务器中抓取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka,http://127.0.0.1:8700/eureka
spring:
  application:
    name: eureka